import { useEffect, useState } from 'react'
import { BrowserRouter, Link, NavLink, Navigate, Outlet, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom'
import { api, ApiError, list } from './api/api'
import './index.css'

const navItems = [{ label: 'Dashboard', path: '/dashboard', icon: '⌂' }, { label: 'Customers', path: '/customers', icon: '◌' }, { label: 'Campaigns', path: '/campaigns', icon: '↗' }, { label: 'Templates', path: '/templates', icon: '▤' }, { label: 'Messages', path: '/messages', icon: '□' }, { label: 'Replies', path: '/replies', icon: '↩' }, { label: 'Opt-outs', path: '/opt-outs', icon: '⊘' }]
const statusTone = { RUNNING: 'green', APPROVED: 'blue', DRAFT: 'gray', PAUSED: 'amber', COMPLETED: 'gray', READ: 'green', DELIVERED: 'blue', SENT: 'blue', QUEUED: 'amber', FAILED: 'red', ACTIVE: 'green', Active: 'green', INACTIVE: 'gray', Approved: 'green' }

function App() {
  useEffect(() => { const expire = () => { if (window.location.pathname !== '/login') window.location.assign('/login?expired=1') }; window.addEventListener('auth-expired', expire); return () => window.removeEventListener('auth-expired', expire) }, [])
  return <BrowserRouter><Routes><Route path="/login" element={<Login />} /><Route element={<ProtectedRoute />}><Route element={<Layout />}><Route path="/" element={<Navigate to="/dashboard" replace />} /><Route path="/dashboard" element={<Dashboard />} /><Route path="/customers" element={<Customers />} /><Route path="/customers/:id" element={<CustomerDetails />} /><Route path="/campaigns" element={<Campaigns />} /><Route path="/campaigns/create" element={<CampaignForm />} /><Route path="/campaigns/:id" element={<CampaignDetails />} /><Route path="/templates" element={<Templates />} /><Route path="/templates/create" element={<TemplateForm />} /><Route path="/templates/:id" element={<TemplateDetails />} /><Route path="/messages" element={<Messages />} /><Route path="/replies" element={<UnsupportedPage title="Replies" detail="The live OpenAPI contract does not expose a replies endpoint." />} /><Route path="/opt-outs" element={<UnsupportedPage title="Opt-outs" detail="The live OpenAPI contract does not expose an opt-outs endpoint." />} /><Route path="/settings" element={<Settings />} /></Route></Route><Route path="*" element={<Navigate to="/dashboard" replace />} /></Routes></BrowserRouter>
}
function ProtectedRoute() { return localStorage.getItem(api.tokenKey) ? <Outlet /> : <Navigate to="/login" replace /> }
function Login() { const navigate = useNavigate(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(new URLSearchParams(window.location.search).get('expired') ? 'Your session has expired. Please log in again.' : ''); const [loading, setLoading] = useState(false); async function submit(event) { event.preventDefault(); if (!email || !password) return setError('Enter your email and password to continue.'); setLoading(true); setError(''); try { const result = await api.login({ email, password }); if (!result?.access_token) throw new ApiError('The server did not return an access token.'); localStorage.setItem(api.tokenKey, result.access_token); navigate('/dashboard') } catch (err) { setError(err.message || 'Unable to sign in.') } finally { setLoading(false) } } return <main className="login-page"><div className="login-art"><div className="brand-mark">L<span>+</span></div><p className="eyebrow">LABORATORY OPERATIONS</p><h1>Customer care,<br /><em>kept in motion.</em></h1><p>Bring inactive customers back with thoughtful, timely outreach.</p><div className="art-line"><span /> Patient engagement platform</div></div><div className="login-panel"><div className="login-panel-inner"><div className="mobile-brand"><div className="brand-mark small">L<span>+</span></div><span>LABFLOW</span></div><p className="eyebrow">ADMIN PORTAL</p><h2>Welcome back</h2><p className="muted">Sign in to manage your customer re-engagement.</p><form onSubmit={submit} className="form-stack"><label>Email<input type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="admin@labflow.com" /></label><label>Password<input type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="Enter your password" /></label>{error && <div className="error-message">{error}</div>}<button className="button primary full" disabled={loading}>{loading ? 'Signing in...' : 'Sign in'} <span>→</span></button></form></div></div></main> }
function Layout() { const [open, setOpen] = useState(false); const navigate = useNavigate(); const location = useLocation(); const current = navItems.find(item => location.pathname.startsWith(item.path)) || navItems[0]; function logout() { localStorage.removeItem(api.tokenKey); navigate('/login') } return <div className="app-shell"><aside className={`sidebar ${open ? 'open' : ''}`}><div className="sidebar-brand"><div className="brand-mark small">L<span>+</span></div><div><strong>LABFLOW</strong><small>LABORATORY CARE</small></div><button className="close-menu" onClick={() => setOpen(false)}>×</button></div><nav>{navItems.map(item => <NavLink key={item.path} to={item.path} onClick={() => setOpen(false)} className={({ isActive }) => isActive ? 'active' : ''}><span className="nav-icon">{item.icon}</span>{item.label}</NavLink>)}</nav><div className="sidebar-bottom"><NavLink to="/settings" onClick={() => setOpen(false)} className={({ isActive }) => isActive ? 'active' : ''}><span className="nav-icon">⚙</span>Settings</NavLink></div></aside>{open && <div className="scrim" onClick={() => setOpen(false)} />}<div className="main-shell"><header className="topbar"><button className="menu-button" onClick={() => setOpen(true)}>☰</button><div><span className="breadcrumb">Admin / </span><strong>{current.label}</strong></div><div className="header-actions"><div className="avatar">AS</div><div className="admin-name">Admin<span>Administrator</span></div><button className="logout" onClick={logout}>Logout</button></div></header><main className="content">{location.pathname === '/dashboard' ? <div className="page-intro"><div><p className="eyebrow">OVERVIEW</p><h1>Good morning, Admin</h1><p className="muted">Live data from your customer re-engagement backend.</p></div></div> : <PageHeader title={current.label} />}<Outlet /></main></div></div> }
function PageHeader({ title }) { return <div className="page-header"><div><p className="eyebrow">ADMIN / {title.toUpperCase()}</p><h1>{title}</h1></div>{title === 'Campaigns' && <Link to="/campaigns/create" className="button primary">＋ Create campaign</Link>}{title === 'Templates' && <Link to="/templates/create" className="button primary">＋ New template</Link>}</div> }
function useRemote(loader, args = []) {
  const [state, setState] = useState({ loading: true, data: null, error: '' })
  // API functions are stable; route arguments are intentionally supplied by callers.
  useEffect(() => {
    let alive = true
    loader(...args).then(data => alive && setState({ loading: false, data, error: '' })).catch(error => alive && setState({ loading: false, data: null, error: error.message || 'Unable to load data.' }))
    return () => { alive = false }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [loader, ...args])
  return state
}
function Loading({ text = 'Loading...' }) { return <div className="state-message"><span className="spinner" />{text}</div> }
function ErrorState({ message }) { return <div className="state-message error-state"><strong>Unable to load data</strong><span>{message}</span></div> }
function EmptyState({ text }) { return <div className="empty-state"><span>⌁</span><h3>{text}</h3><p>The backend returned no records.</p></div> }
function PageState({ state, children, empty }) { if (state.loading) return <Loading />; if (state.error) return <ErrorState message={state.error} />; if (empty && empty(state.data)) return <EmptyState text={empty(state.data)} />; return children(state.data) }
function StatCard({ label, value, tone = 'teal' }) { return <div className="stat-card"><div className={`stat-icon ${tone}`}>◈</div><div><p>{label}</p><strong>{value ?? 0}</strong></div></div> }
function StatusBadge({ status }) { return <span className={`status-badge ${statusTone[status] || 'gray'}`}><i />{status || 'Unknown'}</span> }
function Toolbar({ children }) { return <div className="toolbar">{children}</div> }
function Table({ columns, children }) { return <div className="table-wrap"><table><thead><tr>{columns.map(c => <th key={c}>{c}</th>)}</tr></thead><tbody>{children}</tbody></table></div> }
function formatDate(value) { if (!value) return '—'; const date = new Date(value); return Number.isNaN(date.valueOf()) ? value : date.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }) }
function initials(value = '') { return value.split(' ').map(part => part[0]).join('').slice(0, 2).toUpperCase() }
function number(data, keys) { for (const key of keys) if (data?.[key] !== undefined && data?.[key] !== null) return data[key]; return 0 }

function Dashboard() { const state = useRemote(api.dashboard, []); return <PageState state={state}>{data => { const stats = data || {}; return <><div className="stats-grid"><StatCard label="Total customers" value={number(stats, ['total_customers', 'customers_total', 'totalCustomers'])} /><StatCard label="Inactive customers" value={number(stats, ['inactive_customers', 'inactiveCustomers'])} tone="blue" /><StatCard label="Active campaigns" value={number(stats, ['active_campaigns', 'activeCampaigns'])} tone="lavender" /><StatCard label="Messages sent" value={number(stats, ['messages_sent', 'sent_messages', 'messagesSent'])} tone="orange" /><StatCard label="Delivered" value={number(stats, ['delivered'])} /><StatCard label="Read" value={number(stats, ['read'])} tone="blue" /><StatCard label="Customer replies" value={number(stats, ['replies', 'customer_replies'])} tone="lavender" /><StatCard label="Opt-outs" value={number(stats, ['opt_outs', 'optouts'])} tone="orange" /></div><section className="panel"><div className="panel-heading"><div><p className="eyebrow">LIVE BACKEND SUMMARY</p><h2>Message delivery</h2></div></div><div className="metric-list"><Metric label="Delivered" value={number(stats, ['delivered'])} /><Metric label="Read" value={number(stats, ['read'])} /><Metric label="Failed" value={number(stats, ['failed'])} /><Metric label="Replies" value={number(stats, ['replies', 'customer_replies'])} /></div></section></> }}</PageState> }
function Metric({ label, value }) { return <div className="metric"><div><span>{label}</span><strong>{value ?? 0}</strong></div></div> }

function Customers() { const state = useRemote(api.customers, []); return <PageState state={state} empty={data => !list(data).length ? 'No customers found.' : ''}>{data => <><Toolbar><div className="search"><span>⌕</span><input placeholder="Search is available through the backend list response." disabled /></div><Link to="/customers" className="button subtle">Refresh</Link></Toolbar><Table columns={['Customer', 'Phone', 'Location', 'Last visit', 'WhatsApp consent', 'Status', '']} >{list(data).map(customer => <tr key={customer.id}><td><Link className="person-link" to={`/customers/${customer.id}`}><span className="table-avatar">{initials(customer.name)}</span><strong>{customer.name}</strong></Link><small>{customer.email || '—'}</small></td><td>{customer.phone}</td><td>{customer.location || '—'}</td><td>{formatDate(customer.last_visit)}</td><td>{customer.consent_whatsapp ? <span className="consent yes">✓ Opted in</span> : <span className="consent no">× Disabled</span>}</td><td><StatusBadge status={customer.is_active ? 'ACTIVE' : 'INACTIVE'} /></td><td><Link className="row-action" to={`/customers/${customer.id}`}>View →</Link></td></tr>)}</Table></>}</PageState> }
function CustomerDetails() { const { id } = useParams(); const customer = useRemote(api.customer, [id]); const visits = useRemote(api.visits, [id]); return <><Link to="/customers" className="back-link">← Back to customers</Link><PageState state={customer}>{data => <><div className="detail-hero"><div className="large-avatar">{initials(data.name)}</div><div><h2>{data.name}</h2><p className="muted">Customer ID: {data.id}</p></div><StatusBadge status={data.is_active ? 'ACTIVE' : 'INACTIVE'} /></div><section className="panel"><div className="panel-heading"><h2>Customer information</h2></div><div className="info-grid">{[['Phone', data.phone], ['Email', data.email], ['Location', data.location], ['Date of birth', formatDate(data.date_of_birth)], ['Gender', data.gender], ['Primary test type', data.primary_test_type], ['Last visit', formatDate(data.last_visit)], ['WhatsApp consent', data.consent_whatsapp ? 'Opted in' : 'Disabled']].map(([label, value]) => <div key={label}><span>{label}</span><strong>{value || '—'}</strong></div>)}</div></section><section className="panel"><div className="panel-heading"><h2>Visit history</h2></div><PageState state={visits} empty={value => !list(value).length ? 'No visits found.' : ''}>{value => <Table columns={['Test type', 'Visit date', 'Amount', 'Notes']}>{list(value).map(visit => <tr key={visit.id}><td>{visit.test_type}</td><td>{formatDate(visit.visit_date)}</td><td>{visit.amount || '—'}</td><td>{visit.notes || '—'}</td></tr>)}</Table>}</PageState></section><UnsupportedInline text="Campaign, message, reply, and opt-out history are not exposed by the live customer API contract." /></>}</PageState></> }
function UnsupportedInline({ text }) { return <div className="notice"><span>i</span><div><strong>Unavailable from backend</strong><p>{text}</p></div></div> }

function Campaigns() { const state = useRemote(api.campaigns, []); return <PageState state={state} empty={data => !list(data).length ? 'No campaigns found.' : ''}>{data => <><Toolbar><div className="search"><span>⌕</span><input placeholder="Server-side filters are not defined by this API." disabled /></div><Link to="/campaigns" className="button subtle">Refresh</Link></Toolbar><Table columns={['Campaign name', 'Target days', 'Max customers', 'Status', 'Created', 'Actions']}>{list(data).map(campaign => <tr key={campaign.id}><td><Link className="person-link" to={`/campaigns/${campaign.id}`}><span className="campaign-icon">↗</span><strong>{campaign.name}</strong></Link><small>{campaign.location || '—'} · {campaign.test_type || '—'}</small></td><td>{campaign.target_days}</td><td>{campaign.max_customers}</td><td><StatusBadge status={campaign.status} /></td><td>{formatDate(campaign.created_at)}</td><td><Link className="row-action" to={`/campaigns/${campaign.id}`}>View →</Link></td></tr>)}</Table></>}</PageState> }
function CampaignForm() { const navigate = useNavigate(); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); async function submit(event) { event.preventDefault(); const form = new FormData(event.currentTarget); const body = { name: form.get('name'), description: form.get('description') || null, target_days: Number(form.get('target_days')), max_customers: Number(form.get('max_customers')), test_type: form.get('test_type') || null, location: form.get('location') || null, offer_title: form.get('offer_title') || null, offer_details: form.get('offer_details') || null }; if (!body.name || !body.target_days || !body.max_customers || body.target_days < 1 || body.max_customers < 1) return setError('Enter a name, target days, and maximum customers greater than 0.'); setSaving(true); setError(''); try { await api.createCampaign(body); navigate('/campaigns') } catch (err) { setError(err.message) } finally { setSaving(false) } } return <><Link to="/campaigns" className="back-link">← Back to campaigns</Link><div className="form-page"><div><h2>New campaign</h2><p className="muted">Create a campaign using the backend campaign schema.</p></div><form className="panel form-panel" onSubmit={submit}><FormSection title="Campaign details"><div className="form-grid"><Field label="Campaign name *" name="name" /><Field label="Target inactive days *" name="target_days" type="number" placeholder="90" /><Field label="Maximum customers *" name="max_customers" type="number" placeholder="500" /><Field label="Location" name="location" /><Field label="Test type" name="test_type" /><Field label="Description" name="description" area /></div></FormSection><FormSection title="Offer"><div className="form-grid"><Field label="Offer title" name="offer_title" /><Field label="Offer details" name="offer_details" area /></div></FormSection>{error && <div className="error-message">{error}</div>}<div className="form-actions"><Link className="button subtle" to="/campaigns">Cancel</Link><button className="button primary" disabled={saving}>{saving ? 'Creating...' : 'Create campaign →'}</button></div></form></div></> }
function FormSection({ title, children }) { return <div className="form-section"><h3>{title}</h3>{children}</div> }
function Field({ label, name, type = 'text', placeholder, area }) { return <label>{label}{area ? <textarea name={name} placeholder={placeholder} rows="4" /> : <input name={name} type={type} placeholder={placeholder} />}</label> }
function CampaignDetails() { const { id } = useParams(); const state = useRemote(api.campaign, [id]); const [message, setMessage] = useState(''); async function populate() { setMessage(''); try { const result = await api.populateCampaign(id); setMessage(`Backend populated ${result?.added_count ?? 0} customers.`) } catch (error) { setMessage(error.message) } } return <><Link to="/campaigns" className="back-link">← Back to campaigns</Link><PageState state={state}>{campaign => <><div className="detail-hero"><div className="campaign-icon large">↗</div><div><h2>{campaign.name}</h2><p className="muted">Created {formatDate(campaign.created_at)} · {campaign.location || 'All locations'}</p></div><StatusBadge status={campaign.status} /><button className="button primary" onClick={populate}>Populate audience</button></div><section className="panel"><div className="panel-heading"><h2>Campaign details</h2></div><div className="info-grid">{[['Target days', campaign.target_days], ['Maximum customers', campaign.max_customers], ['Target audience count', campaign.target_audience_count], ['Location', campaign.location], ['Test type', campaign.test_type], ['Offer', campaign.offer_title], ['Created date', formatDate(campaign.created_at)], ['Updated date', formatDate(campaign.updated_at)]].map(([label, value]) => <div key={label}><span>{label}</span><strong>{value || '—'}</strong></div>)}</div>{message && <div className="success-message">{message}</div>}</section><section className="panel"><div className="panel-heading"><h2>Campaign customers</h2></div>{campaign.target_audience?.length ? <Table columns={['Customer ID', 'Campaign ID', 'Reason', 'Status', 'Added at']}>{campaign.target_audience.map(customer => <tr key={customer.id}><td>{customer.customer_id}</td><td>{customer.campaign_id}</td><td>{customer.segment_reason || '—'}</td><td><StatusBadge status={customer.status} /></td><td>{formatDate(customer.added_at)}</td></tr>)}</Table> : <EmptyState text="No campaign customers found." />}</section><UnsupportedInline text="Approve, pause, resume, send, and campaign-results endpoints are not exposed by the live OpenAPI contract." /></>}</PageState></> }

function Templates() { const state = useRemote(api.templates, []); return <PageState state={state} empty={data => !list(data).length ? 'No templates found.' : ''}>{data => <Table columns={['Template name', 'Language', 'Category', 'Status', 'Created', 'Actions']}>{list(data).map(template => <tr key={template.id}><td><Link className="person-link" to={`/templates/${template.id}`}><span className="template-icon">▤</span><strong>{template.name}</strong></Link><small>Backend template</small></td><td>{template.language}</td><td>{template.category}</td><td><StatusBadge status={template.status} /></td><td>{formatDate(template.created_at)}</td><td><Link className="row-action" to={`/templates/${template.id}`}>View →</Link></td></tr>)}</Table>}</PageState> }
function TemplateForm() { const navigate = useNavigate(); const [content, setContent] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); async function submit(event) { event.preventDefault(); const form = new FormData(event.currentTarget); const body = { name: form.get('name'), language: form.get('language') || 'en', category: form.get('category') || 'MARKETING', template_content: content }; if (!body.name || !body.template_content) return setError('Template name and message content are required.'); setSaving(true); setError(''); try { await api.createTemplate(body); navigate('/templates') } catch (err) { setError(err.message) } finally { setSaving(false) } } return <><Link to="/templates" className="back-link">← Back to templates</Link><div className="form-page"><div><h2>New message template</h2><p className="muted">Create a backend WhatsApp template.</p></div><form className="panel form-panel" onSubmit={submit}><div className="template-editor"><div><FormSection title="Template details"><div className="form-grid"><Field label="Template name *" name="name" /><Field label="Language" name="language" placeholder="en" /><Field label="Category" name="category" placeholder="MARKETING" /></div><label>Message content *<textarea rows="13" value={content} onChange={e => setContent(e.target.value)} /></label></FormSection><div className="variables"><strong>Preview variables</strong><span>{['{{customer_name}}', '{{lab_name}}', '{{inactive_days}}', '{{test_type}}', '{{discount}}', '{{offer_title}}', '{{booking_link}}'].map(v => <code key={v}>{v}</code>)}</span></div></div><Preview content={content} /></div>{error && <div className="error-message">{error}</div>}<div className="form-actions"><Link className="button subtle" to="/templates">Cancel</Link><button className="button primary" disabled={saving}>{saving ? 'Saving...' : 'Save template →'}</button></div></form></div></> }
function Preview({ content }) { const preview = content.replaceAll('{{customer_name}}', 'Rahul').replaceAll('{{inactive_days}}', '90').replaceAll('{{lab_name}}', 'LabCare'); return <div className="preview-box"><p className="eyebrow">PREVIEW ONLY</p><h3>WhatsApp message</h3><div className="whatsapp-preview">{preview || 'Enter message content to preview it.'}</div></div> }
function TemplateDetails() { const { id } = useParams(); const state = useRemote(api.template, [id]); return <><Link to="/templates" className="back-link">← Back to templates</Link><PageState state={state}>{template => <><div className="detail-hero"><div className="template-icon large">▤</div><div><h2>{template.name}</h2><p className="muted">{template.language} · {template.category} · Created {formatDate(template.created_at)}</p></div><StatusBadge status={template.status} /></div><div className="template-detail-grid"><section className="panel"><div className="panel-heading"><h2>Message content</h2></div><pre className="message-content">{template.template_content}</pre></section><section className="panel"><Preview content={template.template_content} /></section></div></>}</PageState></> }

function Messages() { const state = useRemote(api.messages, []); return <PageState state={state} empty={data => !list(data).length ? 'No messages found.' : ''}>{data => <Table columns={['Customer ID', 'Campaign ID', 'Template ID', 'Status', 'Sent at', 'Delivered at', 'Read at', 'Failure']}>{list(data).map(message => <tr key={message.id}><td>{message.customer_id}</td><td>{message.campaign_id || '—'}</td><td>{message.template_id || '—'}</td><td><StatusBadge status={message.status} /></td><td>{formatDate(message.sent_at)}</td><td>{formatDate(message.delivered_at)}</td><td>{formatDate(message.read_at)}</td><td>{message.error_message || message.error_code || '—'}</td></tr>)}</Table>}</PageState> }
function UnsupportedPage({ title, detail }) { return <div className="panel"><div className="notice"><span>i</span><div><strong>{title} unavailable</strong><p>{detail} No mock records are shown.</p></div></div></div> }
function Settings() { const state = useRemote(api.settings, []); const [days, setDays] = useState(''); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(''); const displayedDays = days || state.data?.default_inactive_days || ''; async function save() { if (!displayedDays || Number(displayedDays) < 1) return setMessage('Enter inactive days greater than 0.'); setSaving(true); setMessage(''); try { await api.updateInactiveDays(displayedDays); setMessage('Settings saved from the backend.') } catch (error) { setMessage(error.message) } finally { setSaving(false) } } return <PageState state={state}>{() => <div className="settings-page"><section className="panel settings-card"><div className="panel-heading"><div><h2>Re-engagement settings</h2><p className="muted">Current value loaded from the backend.</p></div></div><label className="setting-field">Default inactive days<input type="number" value={displayedDays} onChange={e => setDays(e.target.value)} /><small>Setting key: default_inactive_days</small></label><div className="form-actions"><button className="button primary" onClick={save} disabled={saving}>{saving ? 'Saving...' : 'Save changes'}</button>{message && <span className={message.includes('saved') ? 'success-message' : 'error-message'}>{message}</span>}</div></section></div>}</PageState> }

export default App
